In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv("healthy_eating_balanced.csv")

In [4]:
dataset

,meal_id,meal_name,cuisine,meal_type,calories,protein_g,carbs_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,cooking_method,rating,is_healthy
0,662,Employee Rice,Japanese,Breakfast,357,55.5,39.1,53.1,8.0,0.7,1117,274,Raw,3.7,0
1,1170,Animal Pasta,Mexican,Dinner,328,60.2,40.9,2.7,9.9,5.3,799,136,Raw,3.6,1
2,1602,Be Pasta,Mediterranean,Snack,232,79.0,31.3,4.3,27.2,10.5,326,206,Fried,1.9,1
3,923,Car Rice,American,Dinner,652,41.3,0.6,7.5,25.2,15.9,1602,22,Boiled,3.6,1
4,1154,Real Pasta,Chinese,Lunch,125,68.3,105.9,10.0,16.4,9.8,329,73,Roasted,1.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3621,1241,Hour Rice,Japanese,Dinner,194,37.3,113.8,31.8,7.3,31.6,509,221,Baked,3.8,0
3622,1431,Agree Salad,Chinese,Dinner,233,75.3,67.5,53.5,12.4,9.7,280,44,Steamed,1.3,0
3623,949,Military Salad,Italian,Snack,1149,24.6,18.5,45.9,10.1,48.2,1664,91,Boiled,1.4,0
3624,885,Serious Wrap,Mediterranean,Lunch,287,62.3,13.6,17.3,0.5,10.3,2434,118,Fried,3.9,1
3625,778,Itself Salad,Japanese,Lunch,395,63.6,114.0,0.8,7.3,4.0,247,28,Grilled,4.2,1

In [5]:
# Quan & Qual

In [6]:
def QuanQual(dataset):

    Qual = []
    Quan = []
    for columnName in dataset.columns:
        if(dataset[columnName].dtype == 'O'):
           Qual.append(columnName)
        else:
           Quan.append(columnName)
    return Quan,Qual

In [7]:
QuanQual(dataset)

(['meal_id',
  'calories',
  'protein_g',
  'carbs_g',
  'fat_g',
  'fiber_g',
  'sugar_g',
  'sodium_mg',
  'cholesterol_mg',
  'rating',
  'is_healthy'],
 ['meal_name', 'cuisine', 'meal_type', 'cooking_method'])

In [8]:
quan,qual = QuanQual(dataset)

In [9]:
dataset[quan]

,meal_id,calories,protein_g,carbs_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,rating,is_healthy
0,662,357,55.5,39.1,53.1,8.0,0.7,1117,274,3.7,0
1,1170,328,60.2,40.9,2.7,9.9,5.3,799,136,3.6,1
2,1602,232,79.0,31.3,4.3,27.2,10.5,326,206,1.9,1
3,923,652,41.3,0.6,7.5,25.2,15.9,1602,22,3.6,1
4,1154,125,68.3,105.9,10.0,16.4,9.8,329,73,1.8,1
...,...,...,...,...,...,...,...,...,...,...,...
3621,1241,194,37.3,113.8,31.8,7.3,31.6,509,221,3.8,0
3622,1431,233,75.3,67.5,53.5,12.4,9.7,280,44,1.3,0
3623,949,1149,24.6,18.5,45.9,10.1,48.2,1664,91,1.4,0
3624,885,287,62.3,13.6,17.3,0.5,10.3,2434,118,3.9,1
3625,778,395,63.6,114.0,0.8,7.3,4.0,247,28,4.2,1

In [10]:
dataset[qual]

           meal_name        cuisine  meal_type cooking_method
0      Employee Rice       Japanese  Breakfast            Raw
1       Animal Pasta        Mexican     Dinner            Raw
2           Be Pasta  Mediterranean      Snack          Fried
3           Car Rice       American     Dinner         Boiled
4         Real Pasta        Chinese      Lunch        Roasted
...              ...            ...        ...            ...
3621       Hour Rice       Japanese     Dinner          Baked
3622     Agree Salad        Chinese     Dinner        Steamed
3623  Military Salad        Italian      Snack         Boiled
3624    Serious Wrap  Mediterranean      Lunch          Fried
3625    Itself Salad       Japanese      Lunch        Grilled

[3626 rows x 4 columns]

In [11]:
# Bivariate analysis means analyzing two variables/columns together to understand their relationship or association.

In [12]:
# co-variance

In [13]:
# Covariance = how TWO variables move together.

# Positive covariance → Both variables tend to increase or decrease together. Height ↑ and Weight ↑ → Positive covariance
# Negative covariance → When one increases, the other tends to decrease.Height ↑ and Weight ↓ → Negative covariance
# Covariance ≈ 0 → No clear linear relationship.

In [14]:
dataset[quan].cov()

,meal_id,calories,protein_g,carbs_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,rating,is_healthy
meal_id,338006.714125,7519.116941,-98.582521,-439.475675,-26.184842,-179.467020,-29.531085,-29513.016389,2697.418588,-6.082205,1.411586
calories,7519.116941,84686.851891,-125.029537,101.157637,1263.875201,-6.175890,978.941253,-7841.688455,-1082.242205,6.825383,-72.498069
protein_g,-98.582521,-125.029537,478.030052,-23.548951,-1.072362,6.164931,-3.157482,50.476539,21.431164,1.505639,0.332400
carbs_g,-439.475675,101.157637,-23.548951,1932.631595,-32.529322,-3.100223,-19.621579,-2679.140143,-148.326581,-0.119711,0.543903
fat_g,-26.184842,1263.875201,-1.072362,-32.529322,277.046223,4.445202,60.960582,123.637064,11.494799,1.790486,-5.077834
fiber_g,-179.467020,-6.175890,6.164931,-3.100223,4.445202,81.173175,-4.636860,473.844750,-19.449532,-0.440152,0.113338
sugar_g,-29.531085,978.941253,-3.157482,-19.621579,60.960582,-4.636860,181.604131,-157.206196,-43.224713,0.052185,-3.984772
sodium_mg,-29513.016389,-7841.688455,50.476539,-2679.140143,123.637064,473.844750,-157.206196,515348.070588,-1663.264430,-22.537571,14.604414
cholesterol_mg,2697.418588,-1082.242205,21.431164,-148.326581,11.494799,-19.449532,-43.224713,-1663.264430,7477.161951,-0.081519,-0.337793
rating,-6.082205,6.825383,1.505639,-0.119711,1.790486,-0.440152,0.052185,-22.537571,-0.081519,1.310764,-0.039034
is_healthy,1.411586,-72.498069,0.332400,0.543903,-5.077834,0.113338,-3.984772,14.604414,-0.337793,-0.039034,0.250069

In [15]:
# correlation

In [16]:
# Correlation measures the strength and direction of the relationship between two numerical variables.

# It ranges from -1 to +1.
# +1 → Perfect positive correlation 
# 0 → No linear correlation
# -1 → Perfect negative correlation

In [17]:
dataset[quan].corr()

,meal_id,calories,protein_g,carbs_g,fat_g,fiber_g,sugar_g,sodium_mg,cholesterol_mg,rating,is_healthy
meal_id,1.000000,0.044442,-0.007755,-0.017195,-0.002706,-0.034262,-0.003769,-0.070713,0.053656,-0.009138,0.004855
calories,0.044442,1.000000,-0.019651,0.007907,0.260928,-0.002356,0.249624,-0.037536,-0.043008,0.020486,-0.498183
protein_g,-0.007755,-0.019651,1.000000,-0.024500,-0.002947,0.031296,-0.010716,0.003216,0.011336,0.060149,0.030402
carbs_g,-0.017195,0.007907,-0.024500,1.000000,-0.044455,-0.007827,-0.033120,-0.084893,-0.039019,-0.002378,0.024741
fat_g,-0.002706,0.260928,-0.002947,-0.044455,1.000000,0.029642,0.271775,0.010347,0.007987,0.093958,-0.610060
fiber_g,-0.034262,-0.002356,0.031296,-0.007827,0.029642,1.000000,-0.038190,0.073262,-0.024965,-0.042671,0.025156
sugar_g,-0.003769,0.249624,-0.010716,-0.033120,0.271775,-0.038190,1.000000,-0.016250,-0.037094,0.003382,-0.591304
sodium_mg,-0.070713,-0.037536,0.003216,-0.084893,0.010347,0.073262,-0.016250,1.000000,-0.026794,-0.027422,0.040682
cholesterol_mg,0.053656,-0.043008,0.011336,-0.039019,0.007987,-0.024965,-0.037094,-0.026794,1.000000,-0.000823,-0.007812
rating,-0.009138,0.020486,0.060149,-0.002378,0.093958,-0.042671,0.003382,-0.027422,-0.000823,1.000000,-0.068180
is_healthy,0.004855,-0.498183,0.030402,0.024741,-0.610060,0.025156,-0.591304,0.040682,-0.007812,-0.068180,1.000000

In [18]:
# Multicollinearity & VIF

In [19]:
# Multicollinearity occurs when two or more independent/input variables are highly correlated with each other.

# VIF (Variance Inflation Factor) measures how much the variance of a regression coefficient is increased because of multicollinearity.

# VIF = 1 --> nothing, 1-5 ---> acceptable, >5 ---> high multicollinear, >10 ---> very high/ serious

In [20]:
dataset[quan].columns

Index(['meal_id', 'calories', 'protein_g', 'carbs_g', 'fat_g', 'fiber_g',
       'sugar_g', 'sodium_mg', 'cholesterol_mg', 'rating', 'is_healthy'],
      dtype='object')

In [21]:
# we import "variance_inflation_factor" from statsmodels lib
# this handles the calculation of VIF 
from statsmodels.stats.outliers_influence import variance_inflation_factor

# we drop 'meal_id' because it dosen't do any significant contribution.
# we drop 'is_healthy' because it is the target
X = dataset.drop(['meal_id', 'is_healthy'], axis=1)

# function is defined with an argument "X"
# X is considered as the dataframe that holds the numarical coloum/feature fro which u need to calculate VIF 
def calc_vif(X):
    
    # create a empty variable "vif" to hold the o/p
    vif = pd.DataFrame()
    
    # create a coloum for output variable 
    # "X.columns" pairs each coloumn name directely with its calculated VIF score in the o/p table 
    vif["variables"] = X.columns
    
    # create a seacond coloum name "VIF"
    # x.shape[1] ----> get the total no of columns in X
    # range(X.shape[1]) ----> loops through column indices
    # X.values ----> converts the dataframe into a raw array
    # variance_inflation_factor(X.values, i) ----> calculate the VIF for the ith column
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    return(vif)

In [22]:
calc_vif(dataset[["calories","protein_g","carbs_g","fat_g","fiber_g","sugar_g","sodium_mg","cholesterol_mg","rating"]])

        variables       VIF
0        calories  4.484015
1       protein_g  4.407588
2         carbs_g  3.500959
3           fat_g  3.092491
4         fiber_g  3.596631
5         sugar_g  3.049113
6       sodium_mg  3.679674
7  cholesterol_mg  3.494082
8          rating  6.040060

In [23]:
# ANAVO

In [ ]:
# ANOVA = compares the means of multiple groups.

# p-value < 0.05 → statistically significant difference
# p-value ≥ 0.05 → no statistically significant difference detected

In [35]:
import scipy.stats as stats

stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['calories'],
    dataset[dataset['is_healthy'] == 1]['calories']
)

F_onewayResult(statistic=1196.3405124499604, pvalue=8.644472148015523e-227)

In [ ]:
# pvalue = 8.644472148015523e-227 ----> p > 0.05 = No interaction

In [26]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['protein_g'],
    dataset[dataset['is_healthy'] == 1]['protein_g']
)

F_onewayResult(statistic=3.3527164083160934, pvalue=0.06717626964936349)

In [ ]:
 # pvalue = 0.06717 ---> p > 0.05 = No interaction

In [28]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['carbs_g'],
    dataset[dataset['is_healthy'] == 1]['carbs_g']
)

F_onewayResult(statistic=2.2196722949991963, pvalue=0.1363490015894027)

In [ ]:
# pvalue = 0.136349 ---> p > 0.05 = No interaction

In [29]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['fat_g'],
    dataset[dataset['is_healthy'] == 1]['fat_g']
)

F_onewayResult(statistic=2148.2922377234154, pvalue=0.0)

In [ ]:
# pvalue = 0.0 ---> p < 0.05 fat matters

In [30]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['fiber_g'],
    dataset[dataset['is_healthy'] == 1]['fiber_g']
)

F_onewayResult(statistic=2.294781460368925, pvalue=0.12989668939281848)

In [ ]:
# pvalue = 0.129896 ---> p > 0.05 = No interaction

In [31]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['sugar_g'],
    dataset[dataset['is_healthy'] == 1]['sugar_g']
)

F_onewayResult(statistic=1948.301265112089, pvalue=0.0)

In [ ]:
# pvalue = 0.0 ---> p < 0.05 fat matters

In [32]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['sodium_mg'],
    dataset[dataset['is_healthy'] == 1]['sodium_mg']
)

F_onewayResult(statistic=6.007798596807549, pvalue=0.014289700845022487)

In [ ]:
# pvalue = 0.01428 ---> p < 0.05 = Sodium matters

In [33]:
stats.f_oneway(
    dataset[dataset['is_healthy'] == 0]['cholesterol_mg'],
    dataset[dataset['is_healthy'] == 1]['cholesterol_mg']
)

F_onewayResult(statistic=0.22116666270458132, pvalue=0.6381807139439716)

In [ ]:
# pvalue = 0.63818 ---> p > 0.05 = No interaction

In [36]:
# Hypothesis & T testing

In [ ]:
# Hypothesis testing is a statistical method used to determine whether there is enough evidence to accept or reject a claim about a population.

# Two hypotheses:
# H₀ (Null Hypothesis): No significant difference/relationship exists.
# H₁ (Alternative Hypothesis): A significant difference/relationship exists.

# Using p-value:
# p-value < 0.05 → Reject H₀ → Significant
# p-value ≥ 0.05 → Fail to reject H₀ → Not significant

In [ ]:
# A t-test is a statistical test used to determine whether there is a significant difference between the means of two groups.

In [37]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['calories']
unhealthy = dataset[dataset['is_healthy'] == 0]['calories']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=-34.588155667077146, pvalue=8.644472148028692e-227, df=3624.0)

In [ ]:
# Since the p value(8.6444) is > 0.05 we accept null hypothesis and reject alternative hypothesis

In [38]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['protein_g']
unhealthy = dataset[dataset['is_healthy'] == 0]['protein_g']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=1.8310424376065384, pvalue=0.0671762696494766, df=3624.0)

In [ ]:
# Since the p value(0.06717) is > 0.05 we accept null hypothesis and reject alternative hypothesis

In [39]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['carbs_g']
unhealthy = dataset[dataset['is_healthy'] == 0]['carbs_g']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=1.48985646791869, pvalue=0.13634900158965288, df=3624.0)

In [ ]:
# Since the p value(0.1363) is > 0.05 we accept null hypothesis and reject alternative hypothesis

In [40]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['fat_g']
unhealthy = dataset[dataset['is_healthy'] == 0]['fat_g']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=-46.349673544949745, pvalue=0.0, df=3624.0)

In [ ]:
# Since the p value(0.0) is < 0.05 we reject null hypothesis and accept alternative hypothesis

In [41]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['fiber_g']
unhealthy = dataset[dataset['is_healthy'] == 0]['fiber_g']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=1.5148536102108812, pvalue=0.1298966893930404, df=3624.0)

In [ ]:
# Since the p value(0.12989) is > 0.05 we accept null hypothesis and reject alternative hypothesis

In [42]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['sugar_g']
unhealthy = dataset[dataset['is_healthy'] == 0]['sugar_g']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=-44.13956575581696, pvalue=0.0, df=3624.0)

In [ ]:
# Since the p value(0.0) is < 0.05 we reject null hypothesis and accept alternative hypothesis

In [43]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['sodium_mg']
unhealthy = dataset[dataset['is_healthy'] == 0]['sodium_mg']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=2.4510811077578643, pvalue=0.01428970084504817, df=3624.0)

In [ ]:
# Since the p value(0.0142) is < 0.05 we reject null hypothesis and accept alternative hypothesis

In [44]:
from scipy.stats import ttest_ind

healthy = dataset[dataset['is_healthy'] == 1]['cholesterol_mg']
unhealthy = dataset[dataset['is_healthy'] == 0]['cholesterol_mg']

ttest_ind(healthy, unhealthy)

TtestResult(statistic=-0.4702835981666632, pvalue=0.6381807139432547, df=3624.0)

In [ ]:
# Since the p value(0.63818) is > 0.05 we accept null hypothesis and reject alternative hypothesis